- name: Ensure iptables-services is installed
  package:
    name: iptables-services
    state: present
  when: inventory_hostname == 'haja0013-SRV'

- name: Allow TCP port {{ netcat_port }} from SERVER network ({{ server_network }})
  command: >
    iptables -A INPUT -p tcp -s {{ server_network }} --dport {{ netcat_port }} -j ACCEPT
  when: inventory_hostname == 'haja0013-SRV'

- name: Allow TCP port {{ netcat_port }} from ALIAS network ({{ alias_network }})
  command: >
    iptables -A INPUT -p tcp -s {{ alias_network }} --dport {{ netcat_port }} -j ACCEPT
  when: inventory_hostname == 'haja0013-SRV'

- name: Drop TCP port {{ netcat_port }} from CLIENT network ({{ client_network }})
  command: >
    iptables -A INPUT -p tcp -s {{ client_network }} --dport {{ netcat_port }} -j REJECT
  when: inventory_hostname == 'haja0013-SRV'

- name: Save iptables rules permanently (RHEL 8)
  command: service iptables save
  when: inventory_hostname == 'haja0013-SRV'

- name: Enable and start iptables service
  service:
    name: iptables
    enabled: true
    state: started
  when: inventory_hostname == 'haja0013-SRV'

