- name: Install BIND and utilities
  package:
    name:
      - bind
      - bind-utils
    state: present

- name: Deploy named.conf (templated)
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'

- name: Deploy forward zone file for labtest.lab (only on server/master)
  template:
    src: labtest.lab.zone.j2
    dest: /var/named/labtest.lab.zone
    owner: root
    group: named
    mode: '0644'
  when: inventory_hostname == 'haja0013-SRV'

- name: Deploy reverse zone file for 172.16.30.48 and 172.16.32.48 (only on server/master)
  template:
    src: 16.rev.zone.j2
    dest: /var/named/16.rev.zone
    owner: root
    group: named
    mode: '0644'
  when: inventory_hostname == 'haja0013-SRV'

- name: Create slave zone directory (only on slave)
  file:
    path: /var/named/slaves
    state: directory
    owner: named
    group: named
    mode: '0755'
  when: inventory_hostname == 'haja0013-CTL'

- name: Ensure named service is enabled and started
  service:
    name: named
    state: started
    enabled: true
