- name: Install BIND and utilities
  package:
    name:
      - bind
      - bind-utils
    state: present

- name: Ensure custom zones are included in named.conf (slave)
  blockinfile:
    path: /etc/named.conf
    marker: "# {mark} Ansible managed custom slave zones"
    block: |
      zone "example48.lab" IN {
          type slave;
          masters { 172.16.30.48; };
          file "slaves/slave.example48.lab";
      };

      zone "16.172.in-addr.arpa" IN {
          type slave;
          masters { 172.16.30.48; };
          file "slaves/slave.named.16.172";
      };
  when: inventory_hostname == 'haja0013-CTL'

- name: Ensure custom zones are included in named.conf (master)
  blockinfile:
    path: /etc/named.conf
    marker: "# {mark} Ansible managed custom master zones"
    block: |
      zone "example48.lab" IN {
          type master;
          file "/var/named/labtest.lab.zone";
          allow-transfer { 172.16.32.0/24; };
      };

      zone "16.172.in-addr.arpa" IN {
          type master;
          file "/var/named/16.rev.zone";
          allow-transfer { 172.16.32.0/24; };
      };
  when: inventory_hostname == 'haja0013-SRV'

- name: Deploy forward zone file for labtest.lab (only on server/master)
  template:
    src: labtest.lab.zone.j2
    dest: /var/named/labtest.lab.zone
    owner: root
    group: named
    mode: '0644'
  when: inventory_hostname == 'haja0013-SRV'

- name: Deploy reverse zone file for 172.16.30.48 and 172.16.32.48 (only on server/master)
  template:
    src: 16.rev.zone.j2
    dest: /var/named/16.rev.zone
    owner: root
    group: named
    mode: '0644'
  when: inventory_hostname == 'haja0013-SRV'

- name: Create slave zone directory (only on slave)
  file:
    path: /var/named/slaves
    state: directory
    owner: named
    group: named
    mode: '0755'
  when: inventory_hostname == 'haja0013-CTL'

- name: Ensure named service is enabled and started
  service:
    name: named
    state: started
    enabled: true
